// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpS7Ppu8oX8UeMFlvmvwD5b6vkHf571VI',
    appId: '1:136170554365:web:b8adda930e5b8fe6250f94',
    messagingSenderId: '136170554365',
    projectId: 'uni-rides-app',
    authDomain: 'uni-rides-app.firebaseapp.com',
    storageBucket: 'uni-rides-app.firebasestorage.app',
    measurementId: 'G-KNL123BS21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcBBn7d1SqlKU6Qhlm1tEXY7QyWQnFb0',
    appId: '1:136170554365:android:8393e7c185b13cdf250f94',
    messagingSenderId: '136170554365',
    projectId: 'uni-rides-app',
    storageBucket: 'uni-rides-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvsnKHfCkO7YARcMT8lCPTUHtBZiFRtTY',
    appId: '1:136170554365:ios:92f3fd06805c229c250f94',
    messagingSenderId: '136170554365',
    projectId: 'uni-rides-app',
    storageBucket: 'uni-rides-app.firebasestorage.app',
    iosBundleId: 'com.example.uniRidesV3',
  );
}
